name: "Preevy Up"
description: "Runs the Preevy `up` command"
author: "Livecycle"
inputs:
  profile-url:
    required: true
    description: "The Preevy profile URL"
  args:
    required: false
    description: "Additional args to provide to the `up` command."
  docker-compose-yaml-path:
    required: false
    description: "The path to the docker compose file. Uses current working directory if not provided."
outputs:
  preview-environments-urls:
    description: "The generated URLs of the preview environments create by Preevy, formatted as a markdown table"
    value: ${{ steps.run_preevy.outputs.urls_table }}
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install the Preevy CLI
      shell: bash
      run: npm i -g preevy
    - name: Initialize Preevy
      shell: bash
      run: preevy init --from ${{ inputs.profile-url }}
    - name: Run Preevy
      shell: bash
      id: run_preevy
      run: |
        compose_file_path=${{ inputs.docker-compose-yaml-path }}
        preevy up ${compose_file_path:+-f ${compose_file_path}} ${{ inputs.args }}
        cat << EOF > urls.txt
        | Service | Port | URL |
        |---------|------|-----|
        $(preevy urls ${compose_file_path:+-f ${compose_file_path}} --json | jq -r '.[] | {service, port, url} | join(" | ") | "| " + . + " |" ')
        EOF
        EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
        echo "urls_table<<$EOF" >> $GITHUB_OUTPUT
        cat urls.txt >> $GITHUB_OUTPUT
        echo "$EOF" >> $GITHUB_OUTPUT